import { Metadata } from "next";
import React from "react";
import Navbar from "@/components/moleclues/navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Layout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await getServerSession(authOptions);
  type RolesType = "admin" | "users";

  const rolesType: RolesType = session?.user.roles?.[0];

  return (
    <>
      <Navbar
        name={session.user.name}
        email={session.user.email}
        image={session?.user?.image}
        text={rolesType === "admin" ? "Job List" : ""}
        shadow={false}
      />

      <div className="px-6 py-6 min-h-screen">{children}</div>
    </>
  );
};

export default Layout;
