import { Metadata } from "next";
import React from "react";
import Navbar from "@/components/moleclues/navbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const rolesType = "admin";

  return (
    <>
      <Navbar
        image={rolesType === "admin" ? "/profile.webp" : "/boy.webp"}
        text={rolesType === "admin" ? "Job List" : ""}
        shadow={false}
      />
      <div className="px-6 py-6">{children}</div>
    </>
  );
};

export default Layout;
